<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE Room_list [
   <!ELEMENT Room_list (Room+)>
   <!ELEMENT Room (floor,notes, Residents)>
   <!ATTLIST Room roomtype CDATA #REQUIRED
   				   id CDATA #REQUIRED
                   gender CDATA #REQUIRED>
   <!ELEMENT floor (#PCDATA)>
   <!ELEMENT notes (#PCDATA)>
   <!ELEMENT Residents (Resident+)>
   <!ELEMENT Resident (dob,teleph,dep_grade,checkin,notes)>
   <!ATTLIST Resident name CDATA #REQUIRED
                  	  id CDATA #REQUIRED
                  	  gender CDATA #REQUIRED>
   <!ELEMENT dob (#PCDATA)>
   <!ELEMENT teleph (#PCDATA)>
   <!ELEMENT dep_grade (#PCDATA)>
   <!ELEMENT checkin (#PCDATA)>
]>

<Room_list>
    <Room roomtype="Double" gender="Mixed" id="2">
        <floor>2</floor>
        <notes>Shower</notes>
        <Residents>
            <Resident name="Amapola" gender="Female" id="52">
                <dob>1111-11-11</dob>
                <teleph>726374877</teleph>
                <dep_grade>Independent</dep_grade>
                <checkin>1111-11-11</checkin>
                <notes>She likes badminton</notes>
            </Resident>
        </Residents>
    </Room>
    <Room roomtype="Single" gender="Mixed" id="3">
        <floor>3</floor>
        <notes>Jacuzzi</notes>
        <Residents>
            <Resident name="Anastasio" gender="Male" id="2">
                <dob>1111-11-11</dob>
                <teleph>111111</teleph>
                <dep_grade>Full</dep_grade>
                <checkin>1111-11-11</checkin>
                <notes>He has neumonia and respiratory illnesses</notes>
            </Resident>
        </Residents>
    </Room>
</Room_list>
